backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: static

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Before Heading, name: beforeheading, widget: string },
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Skills,
                    name: skills,
                    widget: list,
                    fields:
                      [
                        { label: Stack Title, name: stacktitle, widget: string },
                        {
                          label: Tech Stack,
                          name: techstack,
                          widget: list,
                          fields:
                          [
                            { label: Text, name: text, widget: string },
                          ],
                        }
                      ],
                  },
                ],
            }
          - {
              label: Jobs,
              name: jobs,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Companies,
                    name: companies,
                    widget: list,
                    fields:
                      [
                        { label: Company Name, name: companyname, widget: string },
                        { label: Job Title, name: jobtitle, widget: string },
                        { label: Date Attended, name: dateattended, widget: string },                        
                        {
                          label: Roles,
                          name: roles,
                          widget: list,
                          fields:
                          [
                            { label: Text, name: text, widget: string },
                          ],
                        }
                      ],
                  },
                ],
            }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Project Featured Image"
        name: "image"
        widget: "image"
        choose_url: true
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true
      - { label: "Post Type", name: "posttype", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Global Settings"
        name: global_settings
        file: site/settings/global_settings.md
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "global-settings",
            }
          - { label: "Site Logo Image", name: "image", widget: "image" }
          - { label: "Site Name", name: "sitename", widget: "string" }
          - { label: "Site Title ", name: "sitetitle", widget: "string", required: false }
          - { label: "Footer Text ", name: "footertext", widget: "string" }
          - {
              label: Navigation Menu,
              name: navigation_menu,
              widget: list,
              fields:
                [
                  { label: Label, name: label, widget: string },
                  { label: Path, name: path, widget: string },
                ],
            }

      - label: "Contact Info"
        name: contact_info
        file: site/settings/contact_info.json
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: "Street", name: "street", widget: "string" }
              - { label: "Street2", name: "street2", widget: "string" }
              - { label: "City", name: "city", widget: "string" }